# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='audioupload',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Trace'),
        ),
    ]
