# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160220_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='trace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Trace'),
        ),
    ]
