# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160220_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='height',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='trace',
            name='width',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='trace',
            name='image',
            field=models.ImageField(height_field='height', upload_to='documents/%Y/%m/%d', width_field='width'),
        ),
    ]
