# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160221_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='image',
            field=models.ImageField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
